name: TheBuild

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a curl command
        run: |
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          -u ${{ secrets.ACCESS_TOKEN }} \
          https://api.github.com/repos/qlimlass/Repo-B/actions/permissions
