name: TheBuild

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run test automation dispatch
        run: |
          curl -X POST https://api.github.com/repos/qlimlass/Repo-B/dispatches \
          -u ${{ secrets.TEST_AUTOMATION_ACCESS_TOKEN }} \
          --data '{"event_type": "qa_tests", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
