name: TheBuild

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a curl command
        run: |
          curl -X POST https://api.github.com/repos/qlimlass/Repo-B/dispatches \
          -u ${{ secrets.ACCESS_TOKEN }} \
