name: test-automation tests
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Show the currently detailed version of Xcode for CLI
        run: xcode-select -p

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: install simulator
        run: xcversion simulators --install='iOS 15.0'
